# Install docker tasks https://docs.docker.com/engine/install/ubuntu/

- name: Uninstall conflicting packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Add Docker GPG apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository into sources list
  vars:
    deb_architecture:
      "aarch64": "arm64"
      "x86_64": "amd64"
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ deb_architecture[ansible_architecture] }}]
      https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: latest
